name: Run CD
on:
  workflow_dispatch:

jobs:
  build-artifacts:
    name: Build Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: setup CI
      uses: lava-nc/ci-setup-composite-action@v1.2
      with:
        repository: 'Lava-DL'

    - name: Build artifacts 
      run: |
        pipx run poetry build

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lava-dl
        path: |
          dist
        retention-days: 10

  test-artifact-install:
    name: Test Artifact Install
    runs-on: ubuntu-latest
    needs: build-artifacts
   
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true

      - name: Download lava-dl artifact
        uses: actions/download-artifact@v3
        with:
          name: lava-dl

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Test artifact tar.gz
        run: |
          python3.9 -m venv artifact-test
          source artifact-test/bin/activate
          artifact=$(ls | grep lava_dl | grep tar)
          pip install --no-input $artifact
          python -c 'import lava.lib.dl.netx'
          python -c 'import lava.lib.dl.slayer'
          pip uninstall -y lava-dl
          deactivate
          rm -rf artifact-test

      - name: Test artifact .whl
        run: |
          python3.9 -m venv artifact-test
          source artifact-test/bin/activate
          artifact=$(ls | grep lava_dl | grep whl)
          pip install --no-input $artifact
          python -c 'import lava.lib.dl.netx'
          python -c 'import lava.lib.dl.slayer'
          pip uninstall -y lava-dl
          deactivate
          rm -rf artifact-test


  test-artifact-use:
    name: Test Artifact With Unit Tests
    runs-on: ubuntu-latest
    needs: [build-artifacts, test-artifact-install]
   
    steps:
      - name: Download lava-dl artifact
        uses: actions/download-artifact@v3
        with:
          name: lava-dl

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Test artifact tar.gz
        run: |
          mkdir tmp
          cd tmp
          cp ../lava* .
          python3.9 -m venv artifact-unittest
          source artifact-unittest/bin/activate
          pip install -U pip
          pip install "nbconvert>=7.2.10,<7.3" pytest>=7.2.0 matplotlib>=3.5.1 ipykernel>=6.15.0 nbformat>=5.3.0
          artifact=$(ls | grep lava_dl | grep tar)
          pip install --no-input $artifact          
          tar -xvf $artifact
          mv ./lava*/tests .
          mv ./lava*/tutorials .
          python -m unittest -vv
          deactivate
          cd ../
          rm -rf tmp

      - name: Test artifact .whl
        run: |
          mkdir tmp
          cd tmp
          cp ../lava* .
          python3.9 -m venv artifact-unittest
          source artifact-unittest/bin/activate
          pip install -U pip
          pip install "nbconvert>=7.2.10,<7.3" pytest>=7.2.0 matplotlib>=3.5.1 ipykernel>=6.15.0 nbformat>=5.3.0
          artifact=$(ls | grep lava_dl | grep whl)
          pip install --no-input $artifact
          # Change $artifact to tar.gz
          artifact=$(ls | grep lava_dl | grep tar)
          tar -xvf $artifact
          mv ./lava*/tests .
          mv ./lava*/tutorials .
          python -m unittest -vv
          deactivate
          cd ../
          rm -rf tmp
